name = "M28AI"
uid = "fnewm028-v286-55b4-92b6-64398e7ge43f"
version = 286
copyright = "CC BY-NC-SA 4.0 Deed"
description = "Competitive AI for FAF (and LOUD, steam and GOG) with strong macro and micro capabilities, AI variants (including M28Easy that disables most micro).  Customise how it plays through the various 'M28 prefix' game options.  Estimated as challenging for a 900-1200 global rated player. Supports campaign missions (as an AI teammate and/or in place of the default campaign AI). More info: https://forum.faforever.com/topic/5331/m28ai-devlog-v1"
author = "maudlin27"
url = ""
icon = "/mods/M28AI/M28AI.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
