name = "M28AI"
uid = "fnewm028-v008-55b4-92b6-64398e7ge43f"
version = 8
copyright = "MIT License"
description = "Work in progress AI, weaker than M27 but faster to run, expected to provide a challenge similar to a 500-800 rated player. Recent changes: Support for FA Campaign M1-6, misc improvements"
author = "maudlin27"
url = ""
icon = "/mods/M28AI/M28AI.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
