--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 13/08/2022 18:01
---
---
local M28Events = import('/mods/M28AI/lua/AI/M28Events.lua')

local function safeGetGlobal(varName)
    local success, value = pcall(function() return _G[varName] end)
    if success then
        return value
    else
        return nil
    end
end

local M28OldACUUnit = safeGetGlobal('ACUUnit') or function()  end
if safeGetGlobal('ACUUnit') then
    _G.ACUUnit = Class(M28OldACUUnit) {
        OnKilled = function(self, instigator, type, overkillRatio)
            M28Events.OnKilled(self, instigator, type, overkillRatio)
            M28OldACUUnit.OnKilled(self, instigator, type, overkillRatio)
        end,
        CreateEnhancement = function(self, enh)
            ForkThread(M28Events.OnEnhancementComplete, self, enh)
            return M28OldACUUnit.CreateEnhancement(self, enh)
        end
    }
end