---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 18/05/2023 22:00
---


local function safeGetGlobal(varName)
    local value = rawget(_G, varName)
    if value then
        return value
    else
        return nil
    end
end

if safeGetGlobal('MakeListFromTarget') then
    local M28OldACreateArmyGroupAsPlatoon = MakeListFromTarget
    MakeListFromTarget = function(Target)
        --Destructive hook - want to replace normal approach so that M28 is treated as a 'human'
        --LOG('MakeListFromTarget: Start of hook')
        local resultList = {}
        if Target.Army then
            resultList[GetArmyBrain(Target.Army)] = true
        end

        if Target.Armies then
            local tblArmy = ListArmies()
            for _, armyName in Target.Armies do
                if armyName == "HumanPlayers" then
                    for iArmy, strArmy in pairs(tblArmy) do
                        --LOG('MakeListFromTarget: Deciding whether to include army, army brain nickname='..(GetArmyBrain(iArmy).Nickname or 'nil')..'; M28AI='..tostring(GetArmyBrain(iArmy).M28AI or false))
                        if ScenarioInfo.ArmySetup[strArmy].Human or GetArmyBrain(iArmy).M28AI then
                            resultList[GetArmyBrain(iArmy)] = true
                        end
                    end
                else
                    for iArmy, strArmy in pairs(tblArmy) do
                        if strArmy == armyName then
                            resultList[GetArmyBrain(iArmy)] = true
                        end
                    end
                end

            end
        end
        return resultList
    end
end


local M28OldAddObjective = AddObjective
AddObjective = function(Type,         -- 'primary', 'bonus', etc
        Complete,     -- 'complete', 'incomplete'
        Title,        -- e.g. "Destroy Radar Stations"
        Description,  -- e.g. "A reason why you need to destroy the radar stations"
        ActionImage,        -- '/textures/ui/common/missions/mission1.dds'
        Target,       -- Can be one of:
-- Units = {unit1, unit2, ...}
-- Areas = {'areaName1', 'areaName2', ...}
        IsLoading,    -- Are we loading a saved game?
        loadedTag     -- If IsLoading is specified, whats the tag?
)
    local oObjective = M28OldAddObjective(Type, Complete, Title, Description, ActionImage, Target, IsLoading, loadedTag)
    ForkThread(import('/mods/M28AI/lua/AI/M28Events.lua').ObjectiveAdded, oObjective, Type, Complete, Title, Description, ActionImage, Target, IsLoading, loadedTag)
    return oObjective
end

local M28OldReclaim = Reclaim
Reclaim = function(Type, Complete, Title, Description, Target)
    ForkThread(import('/mods/M28AI/lua/AI/M28Events.lua').ReclaimTargetObjectiveAdded, Type, Complete, Title, Description, Target)
    return M28OldReclaim(Type, Complete, Title, Description, Target)
end


--Destructive hook:
MakeListFromTarget = function(Target)
    local resultList = {}
    if Target.Army then
        resultList[GetArmyBrain(Target.Army)] = true
    end

    if Target.Armies then
        local tblArmy = ListArmies()
        for _, armyName in Target.Armies do
            if armyName == "HumanPlayers" then
                for iArmy, strArmy in pairs(tblArmy) do
                    if ScenarioInfo.ArmySetup[strArmy].Human or (ScenarioInfo.type == 'campaign_coop' and string.sub(strArmy, 1, 6)  == 'Player') then
                        resultList[GetArmyBrain(iArmy)] = true
                    end
                end
            else
                for iArmy, strArmy in pairs(tblArmy) do
                    if strArmy == armyName then
                        resultList[GetArmyBrain(iArmy)] = true
                    end
                end
            end

        end
    end
    return resultList
end