---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 20/06/2023 07:19
---
local M28OldTransferUnitsOwnership = TransferUnitsOwnership
TransferUnitsOwnership = function(units, toArmy, captured)
    local tCaptured = M28OldTransferUnitsOwnership(units, toArmy, captured)
    ForkThread(import('/mods/M28AI/lua/AI/M28Events.lua').OnCaptured, tCaptured, toArmy, captured)
    return tCaptured
end