---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 17/05/2023 08:04
---

--Redundancy - wouldnt expect any of below to trigger for M28, but this is as an extra redundancy
local M28OldAIBrain = AIBrain
AIBrain = Class(M28OldAIBrain) {
    OnCreateAI =  function(self, planName)
        if self.M28AI then
            --Do nothing
            LOG('Attempted OnCreateAI for baseAI with M28 brain')
        else
            LOG('OnCreateAI for baseAI with no M28AI brain')
            M28OldAIBrain.OnCreateAI(self, planName)
        end
    end,
    CreateBrainShared = function(self, planName)
        if self.M28AI then
            --Do nothing
            LOG('Attempted CreateBrainShared for baseAI with M28 brain')
        else
            LOG('CreateBrainShared for baseAI with no M28AI brain')
            M28OldAIBrain.CreateBrainShared(self, planName)
        end
    end,
    SetCurrentPlan = function(self, bestPlan)
        if self.M28AI then
            --Do nothing
            LOG('Attempted SetCurrentPlan for baseAI with M28 brain')
        else
            LOG('SetCurrentPlan for baseAI with no M28AI brain')
            M28OldAIBrain.SetCurrentPlan(self, bestPlan)
        end
    end,
    InitializeSkirmishSystems = function(self)
        if self.M28AI then
            --Do nothing
            LOG('Attempted to initialise skirmish systems for an M28Brain '..self.Nickname)
        else
            LOG('base-ai: InitialiseSkirmishSystems')
            M28OldAIBrain.InitializeSkirmishSystems(self)
        end
    end,
    InitializeAttackManager = function(self, attackDataTable)
        if self.M28AI then
            --Do nothing
            LOG('Attempted to initialise attack manager for an M28Brain '..self.Nickname)
        else
            LOG('base-ai: InitializeAttackManager')
            M28OldAIBrain.InitializeAttackManager(self, attackDataTable)
        end
    end,
    InitializePlatoonBuildManager = function(self)
        if self.M28AI then
            --Do nothing
            LOG('Attempted to initialise platoon build manager for an M28Brain '..self.Nickname)
        else
            LOG('base-ai: InitializePlatoonBuildManager')
            M28OldAIBrain.InitializePlatoonBuildManager(self)
        end
    end,
    BaseMonitorInitialization = function(self, spec)
        if self.M28AI then
            --Do nothing
            LOG('Attempted to initialise base monitor for an M28Brain '..self.Nickname)
        else
            LOG('base-ai: BaseMonitorInitialization')
            M28OldAIBrain.BaseMonitorInitialization(self, spec)
        end
    end,
}