---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 01/12/2022 08:18
---
function GetUnitLifetimeCount(oUnit)
--Returns what unique (for the unit's aiBrain) count the unit has, i.e. based on the number of previous units with the same blueprint ID
    local iCount = oUnit.M28LifetimeUnitCount

    if iCount == nil then
        if oUnit.GetAIBrain and oUnit.GetUnitId then
            local aiBrain = oUnit:GetAIBrain()
            local sUnitId = oUnit.UnitId
            if aiBrain.M28LifetimeUnitCount == nil then aiBrain.M28LifetimeUnitCount = {} end
            if aiBrain.M28LifetimeUnitCount[sUnitId] == nil then
                aiBrain.M28LifetimeUnitCount[sUnitId] = 1
            else aiBrain.M28LifetimeUnitCount[sUnitId] = aiBrain.M28LifetimeUnitCount[sUnitId] + 1 end
            iCount = aiBrain.M28LifetimeUnitCount[sUnitId]
            oUnit.M28LifetimeUnitCount = iCount
        else
            iCount = 'nil'
        end
    end
    return iCount
end